apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secrets-manager-provider
  namespace: "{{ .Values.namespace }}"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "{{ .Values.awsRegion }}"
