# ---
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: "aws-load-balancer-controller"
# spec:
#   syncPolicy:
#     preserveResourcesOnDeletion: false
#   generators:
#     - clusters: {}
#   template:
#     metadata:
#       name: "{{ metadata.annotations.environment }}-aws-load-balancer-controller"
#     spec:
#       project: default
#       sources:
#         - chart: aws-load-balancer-controller
#           repoURL: https://aws.github.io/eks-charts
#           targetRevision: 1.7.1
#           helm:
#             releaseName: aws-load-balancer-controller
#             values: |
#               clusterName: "{{eks_cluster_name}}"
#               region: "{{ metadata.annotations.aws_region }}"
#               vpcId: "{{vpc_id}}"
#               serviceAccount:
#                 create: true
#                 name: aws-load-balancer-controller
#               ingressClass: alb
#       destination:
#         namespace: "kube-system"
#         name: "{{name}}"
#       syncPolicy:
#         automated: {}
#         syncOptions:
#           - CRDs=CreateReplace
