apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 2.1.3
    releaseName: reloader
    namespace: reloader
    includeCRDs: true
