---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "external-dns"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-external-dns"
    spec:
      project: default
      sources:
        - chart: external-dns
          repoURL: https://kubernetes-sigs.github.io/external-dns/
          targetRevision: 1.16.1
          helm:
            releaseName: external-dns
            values: |
              provider:
                name: aws
              env:
                - name: AWS_DEFAULT_REGION
                  value: "{{ metadata.annotations.aws_region }}"
              policy: sync
      destination:
        namespace: "external-dns"
        name: "{{name}}"
      syncPolicy:
        automated: {}
