---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "metrics-server"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "dev-metrics-server"
    spec:
      project: default
      sources:
        - chart: metrics-server
          repoURL: https://kubernetes-sigs.github.io/metrics-server/
          targetRevision: 3.12.2
          helm:
            releaseName: metrics-server
      destination:
        namespace: "kube-system"
        name: "{{name}}"
      syncPolicy:
        automated: {}
