---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ metadata.annotations.environment }}-metrics-server"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}"
    spec:
      project: default
      sources:
        - chart: metrics-server
          repoURL: https://kubernetes-sigs.github.io/metrics-server/
          targetRevision: 3.12.2
          helm:
            releaseName: metrics-server
      destination:
        namespace: "{{metadata.annotations.aws_load_balancer_controller_namespace}}"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.

