---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "external-secrets"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-external-secrets"
    spec:
      project: default
      sources:
        - chart: external-secrets
          repoURL: https://charts.external-secrets.io
          targetRevision: 0.17.0
          helm:
            releaseName: external-secrets
            values: |
              replicaCount: 1

              image:
                repository: oci.external-secrets.io/external-secrets/external-secrets
                pullPolicy: IfNotPresent
                tag: "v0.17.0"

              installCRDs: true

              serviceAccount:
                create: true
                name: "external-secrets"
        - repoURL: "{{ metadata.annotations.gitops_repo_url }}"
          targetRevision: "{{ metadata.annotations.gitops_repo_revision }}"
          path: "k8s/chart/external-secrets"
          helm:
            releaseName: external-secrets-cluster-store
            valuesObject:
              awsRegion: "{{ metadata.annotations.aws_region }}"
      destination:
        namespace: "external-secrets"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - CRDs=CreateReplace
