---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ingress-nginx"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-ingress-nginx"
    spec:
      project: default
      sources:
        - chart: ingress-nginx
          repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.13.1
          helm:
            releaseName: ingress-nginx
            valuesObject:
              controller:
                ingressClass: nginx
                ingressClassResource:
                  enabled: true
                  name: nginx
                service:
                  type: LoadBalancer
                  loadBalancerClass: service.k8s.aws/nlb
                  annotations:
                    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        - repoURL: https://github.com/kubernetes/ingress-nginx
          targetRevision: controller-v1.13.1
          path: deploy/static/provider/aws
          directory:
            include: "deploy.yaml"
      destination:
        namespace: "ingress-nginx"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CRDs=CreateReplace
          - CreateNamespace=true
