---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ingress-nginx"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-ingress-nginx"
    spec:
      project: default
      sources:
        - chart: ingress-nginx
          repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.13.1
          helm:
            releaseName: ingress-nginx
            values: |
              controller:
                ingressClassResource:
                  name: external-nginx
                service:
                  type: LoadBalancer
                  loadBalancerClass: service.k8s.aws/nlb
                  annotations:
                    service.beta.kubernetes.io/aws-load-balancer-type: "external"
                    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
                    service.beta.kubernetes.io/aws-load-balancer-subnets: "{{ metadata.annotations.public_subnets }}"
      destination:
        namespace: "ingress-nginx"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CRDs=CreateReplace
          - CreateNamespace=true
