---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ingress-nginx"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ metadata.annotations.environment }}-ingress-nginx"
    spec:
      project: default
      sources:
        - chart: ingress-nginx
          repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.13.1
          helm:
            releaseName: ingress-nginx
      destination:
        namespace: "kube-system"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CRDs=CreateReplace
