apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cluster-secret-bootstrap" | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "cluster_addons.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.secret.annotations }}
    {{- range $k, $v := .Values.secret.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- else }}
    {}
    {{- end }}
type: {{ .Values.secret.type | default "Opaque" | quote }}
stringData:
  name: {{ required "values.secret.data.name is required" .Values.secret.data.name | quote }}
  server: {{ (.Values.secret.data.server | default "https://kubernetes.default.svc") | quote }}
  config: {{ .Values.secret.data.config | toJson | quote }}
